name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  schedule:
  - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        php: [8.1, 8.0, 7.4, 7.3]
        laravel: [8.*, 9.*, 10.*]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - php: 8.0
            laravel: 10.*
          - php: 7.4
            laravel: 10.*
          - php: 7.3
            laravel: 10.*
          - php: 8.0
            dependency-version: prefer-lowest
          - php: 7.4
            laravel: 9.*
          - php: 7.3
            laravel: 9.*
          - os: windows-2019
            php: 7.4
          - os: windows-2019
            php: 7.3
    steps:
    - name: Set git to use LF
      if: ${{ matrix.os == 'windows-2019' }}
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: pcov
        extensions: pdo_sqlite, fileinfo

    - name: Install dependencies
      run: |
        composer remove vimeo/psalm --no-update --dev
        composer remove friendsofphp/php-cs-fixer --no-update --dev
        composer require "laravel/framework:${{ matrix.laravel }}" --no-update --no-progress
        composer update --prefer-dist --no-progress

    - name: Execute Unit Tests
      run: composer test-ci

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
          filename: .coverage/cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
          recreate: true
          path: code-coverage-results.md
